import { StyleSheet } from 'react-native';
import {
  ACCENT_TEAL,
  ALBUM_CARD_SIZE,
  ALBUM_GAP,
  HORIZONTAL_PADDING,
  PRIMARY_BACKGROUND,
  PRIMARY_TEXT,
  SECONDARY_TEXT,
  THUMBNAIL_SIZE,
} from '../utils/galleryPathUtils';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: PRIMARY_BACKGROUND },
  selectAllButton: {
    backgroundColor: '#41403D',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
    maxWidth: 96,
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unselectAllButton: { backgroundColor: '#333333' },
  selectAllText: { color: PRIMARY_TEXT, fontSize: 10, fontWeight: '500' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: PRIMARY_BACKGROUND },
  loadingText: { marginTop: 10, color: SECONDARY_TEXT, fontSize: 16 },
  emptyMemories: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  emptyMemoriesText: { color: PRIMARY_TEXT, fontSize: 20, fontWeight: 'bold', marginBottom: 10 },
  emptyMemoriesSubText: { color: SECONDARY_TEXT, fontSize: 16, textAlign: 'center', marginBottom: 20 },
  guestHintBanner: { backgroundColor: 'rgba(34, 178, 166, 0.15)', paddingVertical: 8, paddingHorizontal: 12, marginHorizontal: 12, marginBottom: 8, borderRadius: 8 },
  guestHintText: { color: SECONDARY_TEXT, fontSize: 12, textAlign: 'center' },
  photosContainer: {
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingTop: 14,
    paddingBottom: 24,
  },
  foldersContainer: { paddingHorizontal: HORIZONTAL_PADDING, paddingTop: 14, paddingBottom: 24 },
  folderRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: ALBUM_GAP },
  folderTile: { width: ALBUM_CARD_SIZE, borderRadius: 12, backgroundColor: '#1a1a1a', overflow: 'hidden', alignItems: 'stretch', borderWidth: 1, borderColor: '#474343ff', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 3, elevation: 3 },
  folderTileSpacer: { width: ALBUM_CARD_SIZE, backgroundColor: 'transparent', borderWidth: 0, elevation: 0, shadowOpacity: 0 },
  folderImage: { width: ALBUM_CARD_SIZE, height: ALBUM_CARD_SIZE, borderRadius: 0, backgroundColor: 'transparent' },
  folderPlaceholder: { justifyContent: 'center', alignItems: 'center' },
  folderName: { color: PRIMARY_TEXT, fontSize: 14, fontWeight: '600', paddingHorizontal: 12, paddingTop: 12, paddingBottom: 6 },
  folderCount: { color: SECONDARY_TEXT, fontSize: 11, paddingHorizontal: 12, paddingBottom: 12 },
  folderTileSelected: { borderWidth: 2, borderColor: ACCENT_TEAL },
  folderSelectedOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'transparent', justifyContent: 'center', alignItems: 'center' },
  folderSelectedText: { color: '#FFFFFF', fontSize: 24, fontWeight: 'bold', backgroundColor: ACCENT_TEAL, width: 44, height: 44, borderRadius: 22, textAlign: 'center', lineHeight: 44, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3, elevation: 5 },
  thumbnailContainer: { position: 'relative', margin: 3, borderRadius: 8, overflow: 'hidden', backgroundColor: '#41403D', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 2 },
  thumbnail: { width: THUMBNAIL_SIZE, height: THUMBNAIL_SIZE },
  selectedOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'transparent', justifyContent: 'center', alignItems: 'center' },
  selectedText: { color: '#FFFFFF', fontSize: 24, fontWeight: 'bold', backgroundColor: ACCENT_TEAL, width: 44, height: 44, borderRadius: 22, textAlign: 'center', lineHeight: 44, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3, elevation: 5 },
  photoImageSelected: { borderWidth: 3, borderColor: ACCENT_TEAL },
  photoTimestamp: { position: 'absolute', bottom: 4, left: 4, color: PRIMARY_TEXT, fontSize: 10, backgroundColor: 'rgba(0, 0, 0, 0.7)', paddingHorizontal: 4, paddingVertical: 2, borderRadius: 3 },
  uploadedIndicator: { position: 'absolute', top: 5, right: 5, zIndex: 10 },
  greenDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#4CAF50', borderWidth: 2, borderColor: '#fff', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.3, shadowRadius: 2, elevation: 3 },
  grayDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#9E9E9E', borderWidth: 2, borderColor: '#fff', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.3, shadowRadius: 2, elevation: 3 },
  fullScreenLoaderOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 9999, backgroundColor: 'rgba(0,0,0,0.9)', justifyContent: 'center', alignItems: 'center' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: PRIMARY_BACKGROUND },
  loadingText: { marginTop: 10, color: SECONDARY_TEXT, fontSize: 16 },
});
