import { StyleSheet } from 'react-native';
import {
  ACCENT_TEAL,
  ALBUM_CARD_SIZE,
  ALBUM_GAP,
  HORIZONTAL_PADDING,
  PHOTO_GAP,
  PRIMARY_BACKGROUND,
  PRIMARY_TEXT,
  SECONDARY_TEXT,
  THUMBNAIL_SIZE,
} from '../utils/galleryPathUtils';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PRIMARY_BACKGROUND,
  },
  selectAllButton: {
    backgroundColor: '#41403D',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333333',
    maxWidth: 96,
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unselectAllButton: {
    backgroundColor: '#333333',
  },
  selectAllText: {
    color: PRIMARY_TEXT,
    fontSize: 10,
    fontWeight: '500',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: PRIMARY_BACKGROUND,
  },
  loadingText: {
    marginTop: 10,
    color: SECONDARY_TEXT,
    fontSize: 16,
  },
  emptyMemories: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyMemoriesText: {
    color: PRIMARY_TEXT,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  emptyMemoriesSubText: {
    color: SECONDARY_TEXT,
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
  },
  guestHintBanner: {
    backgroundColor: 'rgba(34, 178, 166, 0.15)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginHorizontal: HORIZONTAL_PADDING,
    marginBottom: 8,
    borderRadius: 8,
  },
  guestHintText: {
    color: SECONDARY_TEXT,
    fontSize: 12,
    textAlign: 'center',
  },
  photosContainer: {
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingTop: 8,
    paddingBottom: 24,
  },
  photoRow: {
    justifyContent: 'flex-start',
    gap: PHOTO_GAP,
    marginBottom: PHOTO_GAP,
  },
  foldersContainer: {
    paddingHorizontal: HORIZONTAL_PADDING,
    paddingTop: 8,
    paddingBottom: 24,
  },
  folderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: ALBUM_GAP,
  },
  folderTile: {
    width: ALBUM_CARD_SIZE,
    borderRadius: 12,
    backgroundColor: '#1a1a1a',
    overflow: 'hidden',
    alignItems: 'stretch',
    borderWidth: 1,
    borderColor: '#474343',
  },
  folderTileSpacer: {
    width: ALBUM_CARD_SIZE,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  folderImage: {
    width: ALBUM_CARD_SIZE,
    height: ALBUM_CARD_SIZE,
    backgroundColor: '#222222',
  },
  folderPlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  folderName: {
    color: PRIMARY_TEXT,
    fontSize: 14,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 4,
  },
  folderCount: {
    color: SECONDARY_TEXT,
    fontSize: 11,
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  folderTileSelected: {
    borderWidth: 2,
    borderColor: ACCENT_TEAL,
  },
  folderSelectedOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: ALBUM_CARD_SIZE,
    height: ALBUM_CARD_SIZE,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  folderSelectedText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    backgroundColor: ACCENT_TEAL,
    width: 44,
    height: 44,
    borderRadius: 22,
    textAlign: 'center',
    lineHeight: 44,
    overflow: 'hidden',
  },
  thumbnailContainer: {
    width: THUMBNAIL_SIZE,
    height: THUMBNAIL_SIZE,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#41403D',
  },
  thumbnail: {
    width: THUMBNAIL_SIZE,
    height: THUMBNAIL_SIZE,
  },
  selectedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    backgroundColor: ACCENT_TEAL,
    width: 44,
    height: 44,
    borderRadius: 22,
    textAlign: 'center',
    lineHeight: 44,
    overflow: 'hidden',
  },
  photoImageSelected: {
    borderWidth: 3,
    borderColor: ACCENT_TEAL,
  },
  photoTimestamp: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    right: 4,
    color: PRIMARY_TEXT,
    fontSize: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 3,
    overflow: 'hidden',
  },
  uploadedIndicator: {
    position: 'absolute',
    top: 5,
    right: 5,
    zIndex: 10,
  },
  greenDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#4CAF50',
    borderWidth: 2,
    borderColor: '#fff',
  },
  grayDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#9E9E9E',
    borderWidth: 2,
    borderColor: '#fff',
  },
  fullScreenLoaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9999,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
