import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  patientNameTopBar: {
    position: 'absolute',
    top: '6%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  patientNameText: {
    color: '#ffffff',
    fontSize: 16,
    fontFamily: 'ProductSans-Bold',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 4,
    overflow: 'hidden',
  },
  container: {
    justifyContent: 'flex-start',
    paddingTop: '12%',
    alignItems: 'center',
    backgroundColor: '#000',
    width: '100%',
    height: '100%',
  },
  blackBackground: {
    width: '100%',
    height: '10%',
    backgroundColor: 'transparent',
    flexDirection: 'row',
    justifyContent: 'center', // Center group of icons
    alignItems: 'center',
    position: 'absolute',
    bottom: '27%',
    gap: 40, // Space between the two centered icons
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 24,
    backgroundColor: 'transparent',
    zIndex: 9999,
  },
  cameraContainer: {
    height: '65%',
    width: '100%',
    backgroundColor: '#000',
  },
  cameraWrapper: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#000',
  },
  previewTouchable: {
    flex: 1,
  },
  preview: {
    flex: 1,
    marginTop: '0%',
    width: '100%',
    height: '100%',
  },
  // ========== UNIFIED BOTTOM CONTROLS STYLES ==========
  // ========== UNIFIED BOTTOM CONTROLS STYLES ==========
  // ========== UNIFIED BOTTOM CONTROLS STYLES ==========
  bottomControlsContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 150, // Fixed height area
    flexDirection: 'row',
    alignItems: 'center', // Vertically center all columns
    justifyContent: 'center',
    zIndex: 100,
    paddingBottom: 40, // More bottom padding as requested
  },
  leftContainer: {
    flex: 1,
    alignItems: 'flex-start', // Push content to Left
    paddingLeft: 30, // Extreme Left spacing
  },
  centerContainer: {
    width: 120, // Fixed width for center button area
    alignItems: 'center',
  },
  rightContainer: {
    flex: 1,
    alignItems: 'flex-end', // Push content to Right
    paddingRight: 30, // Extreme Right spacing
  },
  galleryButtonWrapper: {
    width: 80,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  galleryIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    overflow: 'hidden',
  },
  captureButtonWrapper: {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureIcon: {
    width: 90,
    height: 90,
    resizeMode: 'contain',
  },
  zoomControlBoxWrapper: {
    width: 80, // Increased from 60
    height: 80, // Increased from 60
    justifyContent: 'center',
    alignItems: 'center',
    // Transparent background as requested
    borderRadius: 12,
  },

  // Legacy styles (keeping if needed but overrides prevent usage)
  captureButton: { width: 100, height: 100 },
  galleryButton: { width: 70, height: 70, borderRadius: 35, overflow: 'hidden' },
  focusStatusContainer: {
    position: 'absolute',
    top: '10%',
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    zIndex: 1000,
  },
  focusStatusText: {
    color: '#ffffff',
    fontSize: 16,
    fontFamily: 'ProductSans-Bold',
    textAlign: 'center',
  },
  quitButton: {
    position: 'absolute',
    top: 0,
    bottom: 2,
    right: 10,
    width: 60,
    height: 60,
    borderRadius: 50,
  },
  // captureButton: {
  //   position: 'absolute',
  //   bottom: '10%',
  //   alignSelf: 'center',
  //   width: 100,
  //   height: 100,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   borderRadius: 30,
  // },
  // galleryButton: {
  //   position: 'absolute',
  //   bottom: '13.5%',
  //   left: 20,
  //   width: 50,
  //   height: 55,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   borderRadius: 10,
  // },
  menuButton: {
    position: 'absolute',
    bottom: 97,
    right: 5,
    width: 30,
    height: 30,
    borderRadius: 50,
  },
  menu: {
    flexDirection: 'row-reverse',
    position: 'absolute',
    overflow: 'hidden',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    marginBottom: 150,
    alignItems: 'center',
    bottom: 20,
  },
  menuItemSettings: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 20,
    shadowColor: '#000',
    borderRadius: 20,
  },
  menuItemPol: {
    position: 'absolute',
    bottom: '15%',
    right: '25%', // Adjusted for 3 buttons
    elevation: 20,
    shadowColor: '#000',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemLight: {
    width: 45,
    height: 45,
    elevation: 20,
    shadowColor: '#000',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  boxButtonWrapper: {
    marginLeft: 8,
  },
  polIconContainer: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 20,
    shadowColor: '#000',
  },
  polIconImage: {
    width: 45,
    height: 45,
  },
  icon: {
    width: 45,
    height: 45,
    elevation: 20,
    shadowColor: '#000',
    borderRadius: 20,
  },
  smallerIcon: {
    width: 53,
    height: 53,
  },
  widerPolarisedIcon: {
    width: 57,
    height: 40,
  },
  iconButtonPressed: {
    backgroundColor: '#0D94FF',
    borderRadius: 100,
  },
  sliderContainer: {
    position: 'absolute',
    top: '5%',
    left: 35,
  },
  blocker: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 50,
    backgroundColor: 'transparent',
  },
  //========== EXACT ZOOM BAR STYLES FROM SCREENSHOT ==========
  exactZoomBar: {
    position: 'absolute',
    top: '62.5%',
    left: '5%',
    right: '5%',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    zIndex: 1000,
    overflow: 'hidden', // Important for the moving scale
  },
  exactZoomBarContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  zoomValueDisplay: {
    backgroundColor: 'rgba(255, 175, 32, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 50,
    alignItems: 'center',
  },
  zoomValueText: {
    color: '#000000',
    fontSize: 14,
    fontFamily: 'ProductSans-Bold',
  },
  exactZoomTrack: {
    flex: 1,
    height: 30,
    justifyContent: 'center',
    position: 'relative',
    marginLeft: 12,
    overflow: 'hidden', // Important for the moving scale
  },
  exactZoomTrackLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    top: '50%',
    transform: [{ translateY: -1 }],
    zIndex: 1,
  },
  exactZoomTicks: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    left: 0,
    right: 0,
    top: '50%',
    transform: [{ translateY: -1 }],
    zIndex: 2,
  },
  exactZoomTickContainer: {
    alignItems: 'center',
  },
  exactZoomTick: {
    width: 2,
    height: 8,
    backgroundColor: '#ffffff',
    marginBottom: 12,
  },
  exactZoomTickText: {
    color: '#ffffff',
    fontSize: 10,
    fontFamily: 'ProductSans-Regular',
    marginTop: 2,
  },

  // NEW MOVING SCALE STYLES - EXTENDED
  // Update the moving scale styles
  exactZoomMovingScale: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 3,
  },
  exactZoomMovingTicks: {
    flexDirection: 'row',
    alignItems: 'center',
    height: '100%',
    minWidth: '400%', // Ensure enough width for smooth movement
  },
  exactZoomMovingTickContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '1%', // Use percentage for consistent spacing
  },
  exactZoomMovingTick: {
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
  exactZoomMovingTickMajor: {
    height: 15, // Taller for major ticks (whole numbers)
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  exactZoomMovingTickMedium: {
    height: 10, // Medium for half numbers
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
  exactZoomMovingTickMinor: {
    height: 6, // Shorter for quarter numbers
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },

  // FIXED CENTER INDICATOR (no left positioning)
  exactZoomIndicator: {
    position: 'absolute',
    left: '50%',
    top: 0,
    bottom: 0,
    alignItems: 'center',
    zIndex: 10,
    transform: [{ translateX: -1 }], // Center the indicator
  },
  exactZoomIndicatorLine: {
    width: 2,
    height: 15,
    backgroundColor: '#ffaf20',
  },
  exactZoomIndicatorDot: {
    width: 8,
    height: 8,
    backgroundColor: '#ffaf20',
    borderRadius: 4,
    marginTop: 2,
  },
  // ========== 100x100 ZOOM BOX STYLES ==========
  zoomBoxContainer: {
    position: 'absolute',
    bottom: '13.5%',
    right: 20,
    width: 100, // 100px width
    height: 100, // 100px height
    backgroundColor: 'rgba(30, 30, 30, 0.95)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },

  zoomBoxCurrentDisplay: {
    alignSelf: 'center',
    backgroundColor: 'rgba(60, 60, 60, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    marginBottom: 8,
    minWidth: 40,
    alignItems: 'center',
  },

  zoomBoxCurrentText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: 'ProductSans-Bold',
    textAlign: 'center',
  },

  zoomBoxTrack: {
    width: '100%',
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 8,
  },
  zoomBoxTrackLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    top: '50%',
    transform: [{ translateY: -1 }],
    borderRadius: 1,
  },

  zoomBoxScaleBarsContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 25,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  zoomBoxScaleBars: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'flex-end',
    position: 'relative',
    zIndex: 2,
  },
  zoomBoxScaleBarContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
    height: 25,
  },
  zoomBoxScaleBar: {
    width: 2,
    borderRadius: 1,
    marginBottom: 2,
  },
  zoomBoxScaleBarMajor: {
    height: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  zoomBoxScaleBarMinor: {
    height: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
  },

  zoomBoxFixedIndicator: {
    position: 'absolute',
    bottom: -2,
    left: '50%',
    width: 5,
    height: 25,
    backgroundColor: '#FFD700',
    borderRadius: 3,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 3,
    zIndex: 10,
    transform: [{ translateX: -3 }],
  },

  zoomBoxTouchArea: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: -15,
    bottom: -15,
    backgroundColor: 'transparent',
    zIndex: 5,
  },

  scaleContainer: {
    position: 'absolute',
    bottom: 230,
    backgroundColor: 'rgba(0,0,0,0.5)',
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 13,
    marginBottom: 22,
  },
  scaleFocusContainer: {
    position: 'absolute',
    bottom: 185,
    backgroundColor: 'rgba(0,0,0,0.5)',
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 13,
    marginBottom: 22,
  },
  scaleContentContainer: {
    paddingHorizontal: '44%',
  },
  scaleFocusContentContainer: {
    paddingHorizontal: '44%',
  },
  scaleZoomContentContainer: {
    paddingHorizontal: '45%',
    alignItems: 'center',
  },
  tick: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 20, // INCREASED for less sensitivity
  },
  tickText: {
    color: 'white',
    marginBottom: 5,
  },
  tickFocusText: {
    color: 'white',
    marginBottom: 5,
    marginLeft: 6,
  },
  tickLine: {
    width: 2,
    height: 25,
    backgroundColor: 'white',
    bottom: 0,
  },
  majorTickText: {
    color: '#ffffff',
    fontSize: 12,
    fontFamily: 'ProductSans-Bold',
  },
  majorTickLine: {
    width: 2,
    height: 25,
    backgroundColor: '#ffffff',
  },
  minorTickLine: {
    width: 1,
    height: 15,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  activeTick: {
    backgroundColor: '#ffaf20',
    shadowColor: '#ffaf20',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
  },
  centerLine: {
    position: 'absolute',
    height: 40,
    width: 3,
    backgroundColor: '#f9b039',
    top: '50%',
  },
  currentZoomDisplay: {
    position: 'absolute',
    top: -30,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  currentZoomText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: 'ProductSans-Bold',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000',
    padding: 20,
  },
  errorText: {
    color: '#ffffff',
    fontSize: 18,
    fontFamily: 'ProductSans-Bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  statusContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000',
    padding: 24,
  },
  statusText: {
    color: '#ffffff',
    fontSize: 20,
    fontFamily: 'ProductSans-Bold',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 28,
  },
  statusSubText: {
    color: '#AAAAAA',
    fontSize: 16,
    fontFamily: 'ProductSans-Regular',
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 22,
  },
  statusButton: {
    backgroundColor: '#2a241a',
    borderColor: '#22B2A6',
    borderWidth: 1.5,
    paddingHorizontal: 30,
    paddingVertical: 14,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 200,
    shadowColor: '#22B2A6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  statusButtonText: {
    color: '#22B2A6',
    fontSize: 14,
    fontFamily: 'ProductSans-Bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  permissionButton: {
    backgroundColor: '#22B2A6',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 220,
    shadowColor: '#22B2A6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  permissionButtonText: {
    color: '#000000',
    fontSize: 16,
    fontFamily: 'ProductSans-Bold',
    letterSpacing: 0.5,
  },

  focusIndicator: {
    position: 'absolute',
    width: 120,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  focusOuterRing: {
    width: 100,
    height: 100,
    borderWidth: 2,
    borderColor: '#FFD700',
    backgroundColor: 'transparent',
    borderRadius: 8,
    position: 'absolute',
  },
  focusInnerCrosshair: {
    width: 60,
    height: 60,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#FFD700',
    position: 'absolute',
  },
  focusCorners: {
    position: 'absolute',
    width: 100,
    height: 100,
  },
  focusCorner: {
    position: 'absolute',
    width: 15,
    height: 15,
    borderColor: '#FFD700',
    backgroundColor: 'transparent',
  },
  cornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  cornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  cornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderTopWidth: 0,
    borderRightWidth: 0,
  },
  cornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderTopWidth: 0,
    borderLeftWidth: 0,
  },
  mmScaleContainer: {
    position: 'absolute',
    left: 15,
    top: '10%',
    height: '80%',
    zIndex: 110,
  },
  mmScaleTickRow: {
    position: 'absolute',
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
    transform: [{ translateY: -10 }],
    height: 20,
  },
  mmScaleTickMajor: {
    width: 16,
    height: 2,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
  },
  mmScaleTickMinor: {
    width: 8,
    height: 1.5,
    backgroundColor: 'rgba(255,255,255,0.8)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
  },
  mmScaleTickMedium: {
    width: 12,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
  },
  mmScaleText: {
    color: '#ffffff',
    fontSize: 12,
    fontFamily: 'ProductSans-Bold',
    marginLeft: 6,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  mmScaleLine: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
  },
  mmScaleUnit: {
    position: 'absolute',
    bottom: -25,
    left: 0,
    color: '#ffffff',
    fontSize: 12,
    fontFamily: 'ProductSans-Bold',
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  }
});
